[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "igor",email = "vavilonskiy99@mail.ru"}
]
requires-python = ">=3.12, <4.0"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.poetry.dependencies]
sqlalchemy = "^2.0.41"
fastapi = "^0.115.12"
asyncpg = "^0.30.0"
pydantic = {extras = ["email"], version = "^2.11.5"}
uvicorn = "^0.34.2"
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
python-multipart = "^0.0.20"
argon2-cffi = "^23.1.0"
alembic = "^1.16.1"
psycopg2-binary = "^2.9.10"
python-email = "^0.0.1"
fastapi-mail = "^1.5.0"
celery = "^5.5.2"
redis = "^6.2.0"
asgiref = "^3.8.1"
gevent = "^25.5.1"
pytest = "^8.3.5"
pytest-asyncio = "^1.0.0"
pytest-mock = "^3.14.1"
httpx = "^0.28.1"
async-asgi-testclient = "^1.4.11"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
