"""confirm link

Revision ID: 6f65fbe465d2
Revises: 3e37037a26e3
Create Date: 2025-04-06 19:12:40.501783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f65fbe465d2'
down_revision: Union[str, None] = '3e37037a26e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activate_link', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_activate_link'), 'users', ['activate_link'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_activate_link'), table_name='users')
    op.drop_column('users', 'activate_link')
    # ### end Alembic commands ###
